# 4.0
version: '3.0'
services:

  sql1:
    container_name: medicalofficesql
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Cbmwjmkq23
    ports:
      - "1433:1433"
    volumes:
      - medical_office_sql_data:/var/opt/mssql
    restart: always

  seq:
    image: datalust/seq:latest
    container_name: MedicalOfficeSeq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    depends_on:
      - sql1
    restart: always

  medicalofficewebapi:
    build:
      context: .
      dockerfile: './web_api.dockerfile'
    container_name: medicalofficewebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sql1
      - seq
    restart: always

  medicalofficewebclient:
    build:
      context: .
      dockerfile: './web_client.dockerfile'
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080
    container_name: medicalofficewebclient
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - medicalofficewebapi
    restart: always

volumes:
  medical_office_sql_data:
